###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/roles
###
GET http://localhost:3000/api/products
###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com"
}
###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe"
}
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product_id": 12345,
  "product_name": "Sun Snack",
  "product_price" : 1.99,
  "product_cost": 0.99,
  "note" : "อร่อยดี"
}
###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product_id": 1234,
  "product_name": "Sun Snack",
  "product_price" : 1.99,
  "product_cost": 0.99,
  "note" : "อร่อยดี"
}
###

POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product_id": 12345,
  "product_name": "Sun Snack",
  "product_price" : 2.00,
  "product_cost": 0.99,
  "note" : "อร่อยดี"
}
###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "John Doe5",
  "password": "John12345",
  "firstname": "John",
  "lastname": "Doe"
}

###

GET http://localhost:3000/api/users

###

PUT http://localhost:3000/api/users/5
Content-Type: application/json

{
  "firstname": "Jane",
  "lastname": "Doe"
}

###

DELETE http://localhost:3000/api/users/7

###

POST http://localhost:3000/api/roles
Content-Type: application/json

{
  "name": "User"
}

###

GET http://localhost:3000/api/roles

###

PUT http://localhost:3000/api/roles/6
Content-Type: application/json

{
  "name":"Cilent"
}

###

DELETE http://localhost:3000/api/roles/6

###

GET http://localhost:3000/api/positions

###

POST http://localhost:3000/api/positions
Content-Type: application/json

{
  "Title": "Backend Developer",
  "Description": "Develop RESTful APIs",
  "Level": "Junior"
}

###

POST http://localhost:3000/api/positions
Content-Type: application/json

###

DELETE http://localhost:3000/api/positions/1